package com.linky.offersystem.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.linky.offersystem.bean.OfferItemBean;

import com.linky.offersystem.dao.OfferItemBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig offerItemBeanDaoConfig;

    private final OfferItemBeanDao offerItemBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        offerItemBeanDaoConfig = daoConfigMap.get(OfferItemBeanDao.class).clone();
        offerItemBeanDaoConfig.initIdentityScope(type);

        offerItemBeanDao = new OfferItemBeanDao(offerItemBeanDaoConfig, this);

        registerDao(OfferItemBean.class, offerItemBeanDao);
    }
    
    public void clear() {
        offerItemBeanDaoConfig.getIdentityScope().clear();
    }

    public OfferItemBeanDao getOfferItemBeanDao() {
        return offerItemBeanDao;
    }

}
